FROM node:alpine

WORKDIR /app
COPY package.json .npmrc ./
# Authenticate to GitHub Packages
RUN npm set //npm.pkg.github.com/:_authToken $CR_PAT
RUN npm install --only=prod
COPY . .

ENTRYPOINT ["npm", "start"]