apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tickets.yml
  - orders.yml
  - ingress.yml
  # - gateway.yml
  - dgraph.yml
  # - gateway-dgraph.yml

configMapGenerator:
  - name: client-config
    literals:
      - nextauth-url=https://ticketing-app-kch-chiu.cloud.okteto.net
      - nextauth-url-internal=http://client-srv:3000
      - github-client-id=d003635d4feaa49c2253
      - client-payments-relativeurl=/api/payments
      - client-tickets-relativeurl=/api/tickets
      - client-orders-relativeurl=/api/orders
      - client-stripe-pub=pk_test_51FTiiHFzQH4GYdNSelC82u5p5X10AOC8sglP6ePVWcCy4v376diHYPDPvay5Y5M6m7qCqXOHRKwsjTpaL1baKbhB00VwJrOImM
  - name: gateway-config
    literals:
      - apollo-uplink-url=https://uplink.api.apollographql.com/
      - node-env=production
      - gateway-dgraph-url=http://gateway-srv:4000/graphql
  - name: gateway-dgraph-config
    literals:
      - apollo-uplink-url=https://uplink.api.apollographql.com/
      - node-env=production
      - gateway-dgraph-url=http://gateway-dgraph-srv:5000/graphql
  - name: dgraph-config
    literals:
      - dgraph-alpha-security="whitelist=0.0.0.0/0"

secretGenerator:
  - name: github-client-secret
    literals:
      - github-client-secret=$GITHUB_CLIENT_SECRET
  - name: jwt-key
    literals:
      - jwt-key=$JWT_KEY
  - name: stripe-key
    literals:
      - stripe-key=$STRIPE_KEY
  - name: ticketing-gateway-dgraph-key
    literals:
      - ticketing-gateway-dgraph-key=$TICKETING_GATEWAY_DGRAPH_KEY
  - name: ticketing-gateway-key
    literals:
      - ticketing-gateway-key=$TICKETING_GATEWAY_KEY

generatorOptions:
  disableNameSuffixHash: true
