FROM node:alpine
ARG authToken

WORKDIR /app
COPY package.json .npmrc ./
RUN npm set //npm.pkg.github.com/:_authToken ${authToken}
RUN npm install --only=prod
COPY . .

EXPOSE 9002
ENTRYPOINT ["npm", "start"]